#Spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username:
#    password:
#    hikari:
#      jdbc-url:
#
#  jpa:
#    database-platform: org.hibernate.dialect.postgres
#    hibernate:
#      ddl-auto: update
spring:
  datasource:
    url: jdbc:mysql://localhost/uber_deluxe?createDatabaseIfNotExist=true
    username: jojololamartins686@gmail.com
    password: 1998free

  jpa:
    database-platform: com.mysql.cj.jdbc.Driver
    hibernate:
      ddl-auto: update

    show-sql: true
  h2:
    console:
      enabled: true

  config:
    import:


server:
  port: 9092
